version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/packages/reagent-flow"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/packages/reagent-flow-openai"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/packages/reagent-flow-langchain"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/packages/reagent-flow-langgraph"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/packages/reagent-flow-crewai"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
