version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/packages/reagent-ai"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/packages/reagent-ai-openai"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/packages/reagent-ai-langchain"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/packages/reagent-ai-langgraph"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/packages/reagent-ai-crewai"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
